CREATE TABLE PRODUCT
                    (Product_ID INT IDENTITY PRIMARY KEY,
					 Product_Name VARCHAR(50) NOT NULL,
					 Unit_Prize DEC(10,2) 
					 CHECK(Unit_Prize > 0));

INSERT INTO PRODUCT VALUES('Keybord',120)
INSERT INTO PRODUCT VALUES('Mouse',0)    --ERROR BECAUSE IT NOT SUPPORT THE 0 UNIT_PRIZE IS > 0;
INSERT INTO PRODUCT VALUES('Monitor',5000)
SELECT * FROM PRODUCT

--------------------------------

CREATE TABLE PRODUCT
                    (Product_ID INT IDENTITY PRIMARY KEY,
					 Product_Name VARCHAR(50) NOT NULL,
					 Unit_Prize DEC(10,2) 
					 CONSTRAINT Positive_Prize CHECK(Unit_Prize > 0));

INSERT INTO PRODUCT VALUES('Keybord',120)
INSERT INTO PRODUCT VALUES('Mouse',0)    --ERROR BECAUSE IT NOT SUPPORT THE 0 UNIT_PRIZE IS > 0;
INSERT INTO PRODUCT VALUES('Monitor',5000)
INSERT INTO PRODUCT VALUES('Bike',NULL) ----IT WILL EXCEPT THE NULL AND PRINT THE COLUM IN NULL
INSERT INTO PRODUCT VALUES('Car',NULL)
SELECT * FROM PRODUCT
----------------------------------